[QR]
ECCLevel=7%
Scale=7
[Printer Address]
IP=10.149.1.10
[Port Name]
Com Name=COM5
Lpt Name=LPT1
[Printer Set]
Port Select=3
Printer Select=2
BaudRate Select=19200
[Language Select]
Language=0
[SET]
P76ESW=-112
P80SW=10
[CodePage Select]
CodePage=1252
[NET]
IPADDR=192.168.2.209
MASK=255.255.255.0
GATE=192.168.2.1
SSID=3nStar-HQ-Ofiice
KEY=xTREME@2000
KEYT=6
